spring:
  mvc:
    view:
      prefix: /view/
      suffix: .jsp

logging:
  config: classpath:log4j2.xml

mybatis:
  mapper-locations: classpath:com/wrpys/app/**/model/mapper/*.xml
pagehelper:
  helper-dialect: mysql