profiles:
  active: dev

server:
  port: 9092

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wrpysui_dev
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver