server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  instance:
    #prefer-ip-address: true
    hostname: eureka-server2
  client:
    service-url:
      defaultZone: http://eureka-server1:8761/eureka/,http://eureka-server3:8763/eureka/
  server:
    enable-self-preservation: false

logging:
  config: classpath:log4j2.xml
