server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  instance:
    #prefer-ip-address: true
    hostname: server1
  client:
    service-url:
      defaultZone: http://server2:8762/eureka/,http://server3:8763/eureka/
  server:
    enable-self-preservation: false

logging:
  config: classpath:log4j2.xml