server:
  port: 8762

spring:
  application:
    name: eureka-server

eureka:
  instance:
    #prefer-ip-address: true
    hostname: server2
  client:
    service-url:
      defaultZone: http://server1:8761/eureka/,http://server3:8763/eureka/
  server:
    enable-self-preservation: false

logging:
  config: classpath:log4j2.xml