server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  instance:
    #prefer-ip-address: true
    hostname: server3
  client:
    service-url:
      defaultZone: http://server1:8761/eureka/,http://server2:8761/eureka/
  server:
    enable-self-preservation: false