server:
  port: 8763

spring:
  application:
    name: eureka-server

eureka:
  instance:
    #prefer-ip-address: true
    hostname: server3
  client:
    service-url:
      defaultZone: http://server1:8761/eureka/,http://server2:8762/eureka/
  server:
    enable-self-preservation: false

logging:
  config: classpath:log4j2.xml