spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wrpys/wrpys_workspaces
          search-paths: config
          username: 496732709@qq.com
          password: wrp041527.
server:
  port: 8888